- name:  Deploy app
  hosts: app
  become: true
  vars:
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  - name: Install ruby bundler build-essential
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - ruby-full
      - ruby-bundler
      - build-essential
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: "/home/{{ deploy_user }}/reddit"
      version: monolith   # <-- Указываем нужную ветку
    notify: reload puma
  - name: Bundle install
    bundler:
      state: present
      chdir: "/home/{{ deploy_user }}/reddit" 
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted

