- name:  Deploy app
  hosts: app
  become: true
  vars:
  tasks:
  - name: Install ruby bundler build-essential
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - ruby-full
      - ruby-bundler
      - build-essential
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/appuser/reddit
      version: monolith   # <-- Указываем нужную ветку
    notify: reload puma
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted

