---
- name: Configure db server
  hosts: all
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0 
  tasks:
  - name: add MongoDB public GPG key
    apt_key: url=https://docs.mongodb.org/10gen-gpg-key.asc id=7F0CEB10 state=present validate_certs=False
  - name: add MongoDB stable repository (for Ubuntu)
    apt_repository: repo='deb http://repo.mongodb.org/apt/{{ ansible_distribution|lower }}  {{ ansible_distribution_release|lower }}/mongodb-org/4.2 multiverse' state=present
    when: ansible_distribution == "Ubuntu"
  - name: run the equivalent of "apt-get update" as a separate step
    apt: 
      update_cache: yes
  - name: install mongo db
    apt: 
      name: mongodb-org
      state: present
      force: yes
  - name: Change mongo config file
    template:
      src: mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod
  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

