---
- name: Depoly puma
  hosts: appserver
  tasks:
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/{{ deploy_user }}/reddit
      version: monolith
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/{{ deploy_user }}/reddit 

