---
- name: Fetch the latest version of application code
  git:
    repo: 'https://github.com/express42/reddit.git'
    dest: /home/{{ deploy_user }}/reddit
    version: monolith
  tags: puma-server
- name: Bundle install
  bundler:
    state: present
    chdir: /home/{{ deploy_user }}/reddit
  tags: puma-server
- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  tags: puma-server
- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  tags: puma-server
- name: enable puma
  systemd:
    name: puma
    enabled: yes
  tags: puma-server
- name: start puma
  service:
    name: puma
    state: started
  tags: puma-server

