#!/bin/bash
printf "{\n"
printf "    \"all\": {\n"
printf "         \"children\":\n           {\n\"hosts\": \n{"

# имплементация группировки хостов. В данной работе предпочту не реализовывать.
#echo "groups"
#cat inventory.json |  jq '._meta' | jq '.hostvars' | jq '.[]' | jq '.tags' | jq -c '.items' #> bcode1
#echo "names"
cat inventory.json |  jq '._meta' | jq '.hostvars' | jq '.[]' | jq '.name' > bcode2


#echo "nat_ip-s"
cat inventory.json |  jq '._meta' | jq '.hostvars' | jq '.[]' | jq '.networkInterfaces' | jq '.[0]' | jq '.accessConfigs' | jq '.[0]' | jq '.natIP' > hosts.tmp
while read line
do
	printf $line
	printf ': null,\n'
done < hosts.tmp
rm hosts.tmp

printf "         }       }"
